import cssPseudoClasses from "./references/CSS Pseudo Classes.csv";
import cssSelectors from "./references/CSS Selectors.csv";
import files from "./references/Files.csv";
import htmlAttributes from "./references/HTML Attributes.csv";
import htmlElements from "./references/HTML Elements.csv";
import htmlGlobalAttributes from "./references/HTML Global Attributes.csv";
export const cssPseudoClassesReferences = cssPseudoClasses;
export const cssSelectorsReferences = cssSelectors;
export const filesReferences = files;
export const htmlAttributesReferences = htmlAttributes;
export const htmlElementsReferences = htmlElements;
export const htmlGlobalAttributesReferences = htmlGlobalAttributes;
